# This is the codefresh composition definition for running lodestar-app on Codefresh.

version: '2'
services:
  app:
    image: idearium/lodestar-app
    environment:
      - GO_DNSMASQ_RUNAS=root
    ports:
      - '80'
  lodestar:
    image: idearium/lodestar
    environment:
      - DOMAINS=lodestar.idearium.io,lodestar-ote.idearium.io
      - HOSTED_ZONE_ID=Z7O63FVGCNZNH
