version: '2'

services:
  app:
    build: ./app
    environment:
      - GO_DNSMASQ_RUNAS=root
      - VIRTUAL_HOST=lodestar.local
    expose:
      - "80"
  lodestar:
    build: ./lodestar
    environment:
      - DOMAINS=lodestar.idearium.io,lodestar-2.idearium.io
      - HOSTED_ZONE_ID=Z7O63FVGCNZNH
      - SERVICE=APP
      - CF_URL_APP=http://foo.cf-cd.com:80/someurl

networks:
  default:
    external:
      name: idearium-dev-network
